server:
  port: 8081

spring:
  security:
  # H2 Database 설정
  datasource:
    driver-class-name: org.h2.Driver
    url: 'jdbc:h2:tcp://localhost/~/artistry'
    username: sa
    password:

  # H2 Console 설정
  h2:
    console:
      enabled: true
      path: /h2-console

  # JPA 설정
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
        show_sql: true

  # JMX 설정
  jmx:
    enabled: true
    server:
      port: 9091
      ssl: false
      authenticate: false

  # 이메일 설정
  spring:
    mail:
      host: ${MAIL_HOST}
      port: ${MAIL_PORT}
      username: ${MAIL_USERNAME}
      password: ${MAIL_PASSWORD}
      properties:
        mail:
          smtp:
            auth: true
            starttls:
              enable: true

