server:
  port: 8081
  tomcat:
    max-threads: 200000
    min-spare-threads: 10
    accept-count: 100
    max-connections: 10000000
    max-keep-alive-requests: 1000000
    connection-timeout: 20000000000
    max-swallow-size: -1
    max-http-header-size: 32768

spring:
  security:
  datasource:
    driver-class-name: org.h2.Driver
    url: 'jdbc:h2:tcp://localhost/~/artistry'
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
        show_sql: true
        use_sql_comments: true

  jmx:
    enabled: true
    server:
      port: 9091
      ssl: false
      authenticate: false

  mail:
    host: smtp.gmail.com
    port: 587
    username: dltndus5985@gmail.com
    password: emcx wtls mqcc faqx
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

logging:
  level:
    root: DEBUG
    org.springframework.web: TRACE
    org.hibernate: DEBUG
    com.artistry.artistry: DEBUG
    org.apache.coyote: TRACE
